### ISSUE TITLE
Missing ArmingLevel and Text

### ISSUE THREAD

**Issue by mkizito76** [ubiav/concord4pi#6]
The early code had details about the armiglevel and also displayed the names of the zone in the Text field. It seems this new code has removed that. Is it possible to add that back? 
Examples:
1. This gave me the armingLevel: concord4pi/areapartition/0100/armingLevel (Notice that there no longer an armingLevel node under that path)
2. This gave me the arminglevelText: concord4pi/areapartition/0100/armingLevel/tex
3. This gave me the name of the zone/item (example Front Door) status: concord4pi/areapartition/0100/zones/0002/status (the text here used to be "Front Door" Now it is "None". Notice screen shot Text now says "None")
4. This gave me the motion sensor: concord4pi/areapartition/0100/zones/0005/status (Notice how Text says None in screen shot)

![image](https://user-images.githubusercontent.com/1021010/76354220-0d168f00-62e0-11ea-9a2c-096f3fc25da7.png)

**Comment by ubiav** [comment]
ArmingLevel still exists under an areapartition like this:
concord4pi/areapartition/0500/armingLevel 1
concord4pi/areapartition/0500/armingLevel/text Off
concord4pi/areapartition/0500/armingLevel/user 00FC
concord4pi/areapartition/0500/armingLevel/delayFlags STANDARD|ENTRY DELAY|START DELAY
concord4pi/areapartition/0500/armingLevel/delayTime 0

The zone information being returned is the actual zone status information (e.g. NONE, TRIPPED, FAULTED, etc).  Examples:
concord4pi/areapartition/0100/zones/0006/status 1
concord4pi/areapartition/0100/zones/0006/status/text TRIPPED
