### ISSUE TITLE
Channel text order doesn't match ID value? 

### ISSUE THREAD

**Issue by mvuong1** [ubiav/concord4pi#7]
https://github.com/ubiav/concord4pi/blob/97de1ba8553f9c330b097e03fc3df31e2a392af6/src/concord4pi/data/AlarmAreaPartition.java#L164

MQTT Topic text is "areapartition" but ID value is partitionarea.   For example, /concord4pi/areapartition/0200/siren/ .  Should it be /concord4pi/areapartition/0002/siren/ or /concord4pi/partitionarea/0200/siren/ ?

**Comment by ubiav** [comment]
changed text order as suggested
