### ISSUE TITLE
High CPU utilization

### ISSUE THREAD

**Issue by mvuong1** [ubiav/concord4pi#8]
I ran this program on Raspberry Pi 3B+ and Windows 10 Pro.  On both platform, CPU utilization was at 99% the whole time the program was running.  I had to add Thread.sleep(250) in 3 while loops to slow it down and eliminate the high CPU usage.  Not sure if this is ideal solution since I'm not a Java developer.
MainController.java:start() after line 80
SB2000Controller.java:run() after line 45
MQTTService.java:run() after line 79

Thanks for sharing this program!

**Comment by ubiav** [comment]
Added sleep as suggested.
